services:
    frontend:
        build:
            context: ./frontend
        ports:
            - "5173:5173"
        volumes:
            - ./frontend:/app
            - /app/node_modules
        env_file:
            - ./.env
        depends_on:
            - backend

    backend:
        build:
            context: ./backend
        ports:
            - "5174:5174"
        volumes:
            - ./backend:/app
        env_file:
            - ./.env